// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxEsBw_p7Y5492LYS7YYz7z9TuDEj6mSY',
    appId: '1:716093299703:web:b704a37ea2cc725349ecf2',
    messagingSenderId: '716093299703',
    projectId: 'ai-flow-374403',
    authDomain: 'ai-flow-374403.firebaseapp.com',
    storageBucket: 'ai-flow-374403.appspot.com',
    measurementId: 'G-2Y3GT0HJDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDidgV_bSXpUDtNAtw-6C0T-DtLrYi41Eo',
    appId: '1:716093299703:android:024ccb577976e55a49ecf2',
    messagingSenderId: '716093299703',
    projectId: 'ai-flow-374403',
    storageBucket: 'ai-flow-374403.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Fc9s4OTlP4dh0nlWWWg2pCiioRjDtKs',
    appId: '1:716093299703:ios:af9f9df8d943bad149ecf2',
    messagingSenderId: '716093299703',
    projectId: 'ai-flow-374403',
    storageBucket: 'ai-flow-374403.appspot.com',
    iosClientId: '716093299703-u4jt50j1tr7pt2l4udv6971ubpemla0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Fc9s4OTlP4dh0nlWWWg2pCiioRjDtKs',
    appId: '1:716093299703:ios:af9f9df8d943bad149ecf2',
    messagingSenderId: '716093299703',
    projectId: 'ai-flow-374403',
    storageBucket: 'ai-flow-374403.appspot.com',
    iosClientId: '716093299703-u4jt50j1tr7pt2l4udv6971ubpemla0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiFlow',
  );
}
